### ISSUE TITLE
Patch a schema to allow empty strings

### ISSUE THREAD

**Issue by NicolasEspiau-stilll** [mtbrault/typescript-schema-to-joi#1]
Hello,

I have a type like that:
```typescript
export type PatchDocumentParams = {
  name?: string
  date?: number
  notes?: string
}
```
and a schema loaded like that:
```typescript
const PatchDocumentInputSchema = tsToJoi({
  path: "./src/models/payloads.ts",
  tsconfig: "./tsconfig.json",
  type: "PatchDocumentParams"
})
```

The problem is: when I receive a payload with:
```json
{ "notes": "" }
```
I get a validation error: `"notes" is not allowed to be empty`

How can I path the schema to allow a field to be empty?

Thank you!

**Comment by mtbrault** [comment]
Hello,

Thanks for the feedback. The fix is available on the 1.0.7 version of the package.
